repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.tiktok:tiktok-business-android-sdk:1.5.1'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.android.billingclient:billing:7.1.1'
}

android {
    defaultConfig {
        minSdkVersion 21
    }
}
